### ISSUE TITLE
CSS for TeX/LaTeX logos

### ISSUE THREAD

**Issue by rbeezer** [BooksHTML/mathbook-assets#72]
Dear David,

I've got a small side project to not load MathJaX if we don't have to.  Removing the two logos as math elements will help.  Can you put this CSS in the `add-on.css` for now?  Making an issue so it is here for later.  Works amazingly well.  Rename the "A" and "E" classes if you think they are a bad idea.

```css
/* Adapted from William Hammond (attributed to David Carlisle) */
/* "mathjax-users" Google Group, 2015-12-27 */

.latex-logo {font-family: "PT Serif", "Times New Roman", Times, serif;}

.latex-logo .A {font-size: 75%; text-transform: uppercase; vertical-align: .5ex;
         margin-left: -.48em; margin-right: -.2em;}

.latex-logo .E {vertical-align:-.5ex; text-transform: uppercase;
         margin-left: -.18em; margin-right: -.12em}
```

Usage:

```html
<span class="latex-logo">L<span class="A">a</span>T<span class="E">e</span>X</span>
```
